### ISSUE TITLE
Requirements of Real-Time Personalized DNS 

### ISSUE THREAD

**Issue by someone4194** [microsoft/DNS-Challenge#101]
Hi, I have some questions about the requirements of Track 2(personalized DNS) ...

1. In the paper(ICASSP 2022 DEEP NOISE SUPPRESSION CHALLENGE), **a 6 second clip is precede to the enhanced testclip** to evaluate the model performance. Is it correct?

2. I know that personalized DNS models are expected to work in real-time(maximum delay: 40ms), but **there is no additional time to train(or adapt) the model** after the enrollment speech is given? 

Thanks!

**Comment by motus** [comment]
@hdubey can you please answer these questions? (and maybe we should add some clarification to the readme, too)

**Comment by hdubey** [comment]
@someone4194 Please see this page for definition of real-time pDNS. This is the definition we are using for this challenge.  Can you please clarify your questions? You can extract a speaker embedding from enrollment data which can be appended to input vector for pDNS model. Closing this issues as ask is not specific. Thanks!
