### ISSUE TITLE
Can't load NSNet2-baseline

### ISSUE THREAD

**Issue by a1242758473** [microsoft/DNS-Challenge#102]
Hi,I want to use NSNet2 to enhance 48kHz wav. There are some problems when i run run_nsnet2.py.
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalidMul with domain_version of 13

**Comment by motus** [comment]
@a1242758473 what version of ONNX Runtime are you using? try to upgrade it with e.g. `pip3 install -U onnxruntime` and see if the model loads:
```python
import onnxruntime as ort
model = ort.InferenceSession("NSNet2-baseline/nsnet2-20ms-48k-baseline.onnx")
```
I've just tried it on my PC with ORT v 1.8.0 and everything seems to be fine.

P.S. If it still fails for you after updating the ORT, please open another issue and attach your stack trace. Thank you!
