### ISSUE TITLE
Duplication in emotional, read and spanish clean speech subsets

### ISSUE THREAD

**Issue by amie-roten** [microsoft/DNS-Challenge#103]
Hello,

I've been doing a bit of inspection of the training datasets provided and noticed that in a few of the speech subsets, .wav files are repeated in the base directory (e.g. 'read_speech'), but also in a subdirectory (e.g. 'read_speech/read_speech'). Do these files differ in some way? On a cursory glance, they don't appear to. The duplicates are included in the checksum .csv as well. 

Thanks,
Amie

**Comment by hdubey** [comment]
yes, that's duplicate

**Comment by amie-roten** [comment]
FYI, I found similar issues in the emotional and spanish subsets.
