### ISSUE TITLE
invalid syntax when trying to run nsnet_eval_local.py

### ISSUE THREAD

**Issue by haroitman** [microsoft/DNS-Challenge#11]
Hi
I´m trying to run nsnet_eval_local.py but I´m geting a SyntaxError: invalid syntax related to <!DOCTYPE html> at the beginning of the file.
Any advice of what could be causing this?
Thanks

**Comment by chandanka90** [comment]
Hi, can you please share more details about this error? A snapshot of the entire error will be useful. Thanks!

**Comment by haroitman** [comment]
Hi
Thanks
<img width="209" alt="Capture1" src="https://user-images.githubusercontent.com/62653092/77800198-095f6800-7055-11ea-85da-066ed1cff986.PNG">

**Comment by haroitman** [comment]
The problem was due to have downloaded separately some files instead of have downloaded all the repository. Thanks
