### ISSUE TITLE
DNSMOS Samplerate

### ISSUE THREAD

**Issue by LiuAoYu510** [microsoft/DNS-Challenge#113]
I noticed that the DNSMOS local is a 16KHz model, which could not infer on full bandwidth audios unless downsampled. If possible, would you be willing to open source such a 48KHz model, since I found that an audio of 48KHz may get a totally different score from its downsampled one. As far as I know, this could happen under the condition that the SNR(signal to noise ratio) varies greatly along the frequency axis. Thanks!

**Comment by stonelazy** [comment]
@LiuAoYu510 Jst wanted to know whether you have found any solution for measuring the 48kHz model quality. If not DNSMOS, do we have any other better metric for getting prediction quality of full band data ?

**Comment by vishakg** [comment]
We are still working on a full band model. We don't have an ETA for that yet. On the other hand, we found the 16khz model gives a pretty good stack rank of the full band noise suppression model, w.r.t subjective scores.
