### ISSUE TITLE
DNSMOS Missing p808 Model

### ISSUE THREAD

**Issue by jhkonan** [microsoft/DNS-Challenge#116]
The DNSMOS repo has the p835 model, but not the p808 model. I am reproducing and analyzing models made on the DNS-2020 data set, so I am only able to use the p808 metric. When might this be released?

**Comment by isgursoy** [comment]
following

**Comment by DavidLBick** [comment]
I would also find this very useful for my work.

**Comment by vishakg** [comment]
P.808 model updated to the repo.
