### ISSUE TITLE
Meaning of SIG, BAK and OVR

### ISSUE THREAD

**Issue by domcross** [microsoft/DNS-Challenge#119]
Thanks for your fantastic work. What do the output values (of `dnsmos_local.py`) SIG, BAK and OVR stand for? My guess is signal, background and overall? Maybe I am missing something but I couldn't find any hint in the paper on it.

**Comment by omidko** [comment]
Hey, I had the same question and found this one: 
> The subjective test ITU-T P.835 [2] provides the speech
quality (SIG), background noise quality (BAK), and overall
quality (OVRL). 

Source: https://arxiv.org/pdf/2110.01763.pdf

**Comment by rosscutler** [comment]
That's correct. The paper is noted in https://github.com/microsoft/DNS-Challenge.

**Comment by rosscutler** [comment]
Resolved

**Comment by shenbuguanni** [comment]
> Resolved

I just scored dns5's noisy blind test set with dns_local version, and found that the noisy score is much different from the mos score provided by the official website. What's the problem, please?
