### ISSUE TITLE
No enhanced audios are generated

### ISSUE THREAD

**Issue by haroitman** [microsoft/DNS-Challenge#12]
Hi. I´m trying to run NSNet. I don´t get errors but no enhanced audios are generated in the assigned folder. In a Linux terminal I get the following message (I´me testing it with 6 .wav audios):
2020-04-01 09:49:30,581 DEBUG NSNet local workers start with 6 input files
2020-04-01 09:49:30,589 INFO NSNet local workers complete

Could you advice what could be the issue? 

Thank you

**Comment by asarsembayev** [comment]
Hi!

I also do not receive processed files

![image](https://user-images.githubusercontent.com/7770267/78171712-b29fc700-7476-11ea-9476-4ad2825a3e8e.png)

I found that there should be a log output
`logging.debug("Writing to: %s", outpath)`
in the end, but I haven't obtained it

**Comment by asarsembayev** [comment]
> Hi!
> 
> I also do not receive processed files
> 
> ![image](https://user-images.githubusercontent.com/7770267/78171712-b29fc700-7476-11ea-9476-4ad2825a3e8e.png)
> 
> I found that there should be a log output
> `logging.debug("Writing to: %s", outpath)`
> in the end, but I haven't obtained it

it's all fine. the mistake I made was stupid. I have forgotten to directly put the whole name of the model. I have written `nsnet-baseline-dnschallenge` instead of `nsnet-baseline-dnschallenge.onnx` .
Sorry =)

**Comment by asarsembayev** [comment]
> Hi. I´m trying to run NSNet. I don´t get errors but no enhanced audios are generated in the assigned folder. In a Linux terminal I get the following message (I´me testing it with 6 .wav audios):
> 2020-04-01 09:49:30,581 DEBUG NSNet local workers start with 6 input files
> 2020-04-01 09:49:30,589 INFO NSNet local workers complete
> 
> Could you advice what could be the issue?
> 
> Thank you

have you double-checked if your command is correct? in my case, the reason was in missing extension of the model

**Comment by haroitman** [comment]
Yes, the command was not right. Thank you very much
