### ISSUE TITLE
Inquiry about DNSMOS P.835

### ISSUE THREAD

**Issue by jyn282** [microsoft/DNS-Challenge#123]
Hi, I have several questions about DNSMOS.

I found that DNSMOS P.835 model was recently updated(around 24th May) and new model seems quite different from previous dnsmos_local model.
 
For example, in case of blind test set (https://dns4public.blob.core.windows.net/dns4archive/blind_testset_bothtracks.zip),  the differences between two models I measured are as follow. (it's not personalized model)

  | SIG | BAK | OVL
-- | -- | -- | --
Prev DNSMOS P.835 | 4.124 | 3.047 | 3.264
new DNSMOS P.835 raw | 3.492 | 2.153  | 2.305 
new DNSMOS P.835 | 3.195 |   2.375 | 2.229

So my questions are,
 - In result csv file, the two results (raw version, averaged version) are saved. Do I take averaged version value instead of raw ?
 - Is the previous model used in the previous DNS-challenge4(2022) and published paper ? If so, is the new model better suited  to subjective results?  Since I'll use this parameters for NR model evaluation(and comparing published paper values), so it would be helpful to understand the difference from the existing model.

**Comment by Abalam-29895** [comment]
Can you please explain what is the difference between "sig","bak" and ovl?

**Comment by jyn282** [comment]
@Abalam-29895  It's objective metrics based on P.835. Speech quality(SIG), background noise quality (BAK) and the overall quality (OVRL) of audio. You can find detail in the paper. [DNSMOS P.835 paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9746108&casa_token=pWjicDnutv8AAAAA:3iRN6okYKuxwzoVhSbc_W74l1Isle3tFwt5PR6m30u-xTmncVNo1Q53nH-jz0SYEN2K8hVQGWDk2oME)

**Comment by Abalam-29895** [comment]
Thank you, that was helpful

**Comment by harsh-agarwal** [comment]
Do yo happen to know the difference between raw and normal score?

**Comment by jyn282** [comment]
@harsh-agarwal  Not 100% sure, but based on the `dnsmos_local.py`, *_raw parameters are DNSMOS P.835 model output of segmented audio input features. 
On the other hands, normal parameters (w/o tagging raw) are weighted sum of *_raw parameters. I guess these weighting is adjust evaluation parameters to better fit the subjective results.  But I couldn’t find the documents how these weighting is came out.

**Comment by vishakg** [comment]
@harsh-agarwal and @jyn282 sorry for the delay in the response. Like @jyn282 explained the raw scores are without the polyfit. Polyfit is needed to uncompress the scores and make it more understandable. To compare to subjective scores one would use the polyfit output whereas to compare different models one would use the raw scores.

**Comment by shenbuguanni** [comment]
> @harsh-agarwal and @jyn282 sorry for the delay in the response. Like @jyn282 explained the raw scores are without the polyfit. Polyfit is needed to uncompress the scores and make it more understandable. To compare to subjective scores one would use the polyfit output whereas to compare different models one would use the raw scores.

I just scored dns5's noisy blind test set with dns_local version(not personal), and found that the noisy score is much different from the mos score provided by the official website. What's the problem, please?

**Comment by zdj97** [comment]
Hi, what is the meaning of these metrics?

    def get_polyfit_val(self, sig, bak, ovr, is_personalized_MOS):
        if is_personalized_MOS:
            p_ovr = np.poly1d([-0.00533021,  0.005101  ,  1.18058466, -0.11236046])
            p_sig = np.poly1d([-0.01019296,  0.02751166,  1.19576786, -0.24348726])
            p_bak = np.poly1d([-0.04976499,  0.44276479, -0.1644611 ,  0.96883132])
        else:
            p_ovr = np.poly1d([-0.06766283,  1.11546468,  0.04602535])
            p_sig = np.poly1d([-0.08397278,  1.22083953,  0.0052439 ])
            p_bak = np.poly1d([-0.13166888,  1.60915514, -0.39604546])

        sig_poly = p_sig(sig)
        bak_poly = p_bak(bak)
        ovr_poly = p_ovr(ovr)

        return sig_poly, bak_poly, ovr_poly
