### ISSUE TITLE
Personalized DNSMOS input format

### ISSUE THREAD

**Issue by kevinkepp** [microsoft/DNS-Challenge#126]
What is the input format for the personalized DNSMOS estimator?
Do we need to prepend the 5s enrollment speech plus 1s pause like in the modified P.835 described in the challenge paper?

**Comment by fjiang9** [comment]
@kevinkepp Hi, have you figured out how to use the personalized DNSMOS estimator? I have the same concern.

**Comment by vishakg** [comment]
The personalized model just penalizes the neighbor speak at the moment. We are working on a model that will utilize enrolment data to correctly compute the MOS. Stay tuned.
