### ISSUE TITLE
2022 winning Models

### ISSUE THREAD

**Issue by taucontrib** [microsoft/DNS-Challenge#138]
Anyone here can provide me with further information regarding the winning models of the 2022 challenge?
I couldn't find out anything beyond there names on the microsoft website. 
Thanks!

**Comment by sangeet2020** [comment]
https://ieeexplore.ieee.org/document/9746610
First rank on DNS-4 challenge 2022

**Comment by Ludvig-Joborn** [comment]
Winning team's "repository": [https://github.com/echocatzh/MTFAA-Net](https://github.com/echocatzh/MTFAA-Net).
It's missing training code, but perhaps you can create that yourself.
Other than that, you can find the second placing team on ModelScope (what seems to be a Chinese equivalent of HuggingFace): [https://modelscope.cn/models/damo/speech_frcrn_ans_cirm_16k/summary](https://modelscope.cn/models/damo/speech_frcrn_ans_cirm_16k/summary).
(Use translate extension to get English text, I managed to fetch a working model this way)

**Comment by taucontrib** [comment]
Thank you ! :)
