### ISSUE TITLE
multiprocessor lacks good error message

### ISSUE THREAD

**Issue by GoldenRed** [microsoft/DNS-Challenge#15]
I am running Linux-on-Windows so the initial source clean/speech and noise directories set in the .cfg file were not true. When I ran the noisyspeech_synthesizer_multiprocessing.py it crashed at row 73, idx = idx_counter.value % np.size(source_files), as the source_files was empty, making np.size(source_files) == 0, which in tun meant modulo by 0 or division by zero.

noisyspeech_synthesizers_singleprocess.py raised me a proper error code (couldnt find clean files) which was helpful. Could be worth adding the same error code to the multiprocessing file as well.

**Comment by jkzhang7** [comment]
Agreed. I also suppose it might be better including 'Noticing Linux's directory is using slash rather than backslash'. Since sometimes ppl would overlook it in config...
