### ISSUE TITLE
The dimensions of model_v8.onnx 

### ISSUE THREAD

**Issue by chanyub** [microsoft/DNS-Challenge#152]
After 'Add P.808 MOS to DNSMOS P.835 scores' commit, 'dnsmos_local.py' is not running.
The dimensions of 'model_v8.onnx' is 901, not 900. The pre-commit version runs well. Please check. Thank you.

**Comment by TUdayKiranReddy** [comment]
Facing the same problem. Changing the below parameter to 9.00 is creating an issue with the model 'sig_bak_ovr.onnx' https://github.com/microsoft/DNS-Challenge/blob/84f20394fed911dde0d08b232bb33cae66996629/DNSMOS/dnsmos_local.py#L20

**Comment by ahmetgunduz** [comment]
Facing the same issue.

**Comment by caiyxxxxx** [comment]
Facing the same issue.

**Comment by jiang-wenbin** [comment]
**+1**

**Comment by vishakg** [comment]
Sorry for the delay in fixing the issue. I pushed a fix today.
