### ISSUE TITLE
Server connection times out, downloading DNS4 dataset

### ISSUE THREAD

**Issue by Student204161** [microsoft/DNS-Challenge#153]
A couple of days ago I ran the shellfile to download the DNS4 dataset on my institutions HPC system (running Scientifc Linux 7) and came back today to find that 9/10 of the files were incomplete, and seemingly the download was timed out. Trying to debug, I also ran it on my windows desktop. The specific error is:
curl: (56) Recv failure: Connection was reset
I also tested using direct links of some of the blobs using Chrome and almost all of the time the download fails by first stalling to a speed of 0, at anywhere between 0.1 and 4.9gb out of 5gb downloaded. 
I have tried clearing DNS-cache and disabling firewalls but I still run into the same problem. 

Previously, in late November* I downloaded a snipptet of the dataset and I did not run into any issues... Which leads me to suspect that the problem may have something to do with the server being busy since many people are downloading the DNS5-dataset.

I have also tried to look into whether it would be possible to resume a interrupted download using the -C option in curl, which would more or less fix the issue, but I get the error,
curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.

Thanks for the attention & Merry Christmas

**Comment by Zetman22** [comment]
you can try downloading by colab and save to your google drive, the connection between colab and azure is much more stable

**Comment by Student204161** [comment]
Thanks @Zetman22 for the advice. I setup the download with google colab (pro version if that matters) and the first few blobs are downloaded without any problems.
