### ISSUE TITLE
Request: labels for the datasets

### ISSUE THREAD

**Issue by tracek** [microsoft/DNS-Challenge#16]
Hi,

Can you supply labels associated with the audio? The README gives impression that you have them, but they are nowhere to be found in the repo. It would help a good deal to combat the bias. For starter, we could subsample classes that are overrepresented.

**Comment by chandanka90** [comment]
The ground truth for the noise suppression task is clean speech. The clean speech is provided here https://github.com/microsoft/DNS-Challenge/tree/master/datasets/clean. The provided scripts will generate noisy-clean pairs for training deep noise suppression models.

**Comment by tracek** [comment]
I was asking for the noise labels, i.e. mapping of a file name to the noise class.
