### ISSUE TITLE
Conversion of NSNET to onnx.js

### ISSUE THREAD

**Issue by hchintada** [microsoft/DNS-Challenge#18]
Can the nsnet be converted to onnx.js?

Would be exciting to try it on a browser

**Comment by chandanka90** [comment]
Probably... But we never tried

**Comment by huningxin** [comment]
There is a web version of NSNet2 available at https://webmachinelearning.github.io/webnn-samples/nsnet2/.

It is based on [WebNN API](https://webmachinelearning.github.io/webnn/) and [TF.js polyfill](https://github.com/webmachinelearning/webnn-polyfill). You can find more details in WebNN [explainer](https://github.com/webmachinelearning/webnn/blob/master/explainer.md) and https://github.com/webmachinelearning/webnn-samples/tree/master/nsnet2.

**Comment by chandanka90** [comment]
Nice work!
