### ISSUE TITLE
git lfs error while downloading dataset

### ISSUE THREAD

**Issue by hchintada** [microsoft/DNS-Challenge#20]
Below is the error I'm getting while trying to clone the repo:

> Cloning into 'DNS-Challenge'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 132377 (delta 0), reused 0 (delta 0), pack-reused 132374
Receiving objects: 100% (132377/132377), 23.95 MiB | 2.25 MiB/s, done.
Resolving deltas: 100% (134/134), done.
Updating files: 100% (132177/132177), done.
Downloading datasets/clean/book_00648_chp_0004_reader_11560_3.wav (992 KB)
Error downloading object: datasets/clean/book_00648_chp_0004_reader_11560_3.wav (a6a917c): Smudge error: Error downloading datasets/clean/book_00648_chp_0004_reader_11560_3.wav (a6a917c0a7fdcdce1147c20a77ef5eeb79ee54ffdd69d4fcb4b13996d978fef5): batch response: Post "https://github.com/microsoft/DNS-Challenge.git/info/lfs/objects/batch": dial tcp: lookup github.com: no such host

> Errors logged to D:\TF\DTLN-tfjs\DNS-Challenge\.git\lfs\logs\20200716T111635.8111709.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: datasets/clean/book_00648_chp_0004_reader_11560_3.wav: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by adobles96** [comment]
Did you ever solve this issue? I'm having a similar problem

**Comment by tvuong123** [comment]
Anyone else having it take forever to download the dataset?

**Comment by liziru** [comment]
Any solutions? I'm having a similar problem too.

**Comment by adobles96** [comment]
@liziru @tvuong123 I managed to solve the issue by cloning via ssh instead of https. Hope this helps.
