### ISSUE TITLE
datasets size

### ISSUE THREAD

**Issue by 20050710212** [microsoft/DNS-Challenge#22]
Thanks for sharing these datasets.

I have already downloaded 140GB, but the **.git** folder takes about 70GB. Could you tell me how much disk space should be prepared before git clone? 

Thank you so much.

**Comment by 20050710212** [comment]
I have already clone the datasets. It takes about 250GB.

**Comment by wangtao2668129173** [comment]
hi，we try it download (git clone ), but  I find it about 1.7G, and audio unreadable.

**Comment by zhaoyj1122** [comment]
> hi，we try it download (git clone ), but I find it about 1.7G, and audio unreadable.

What downloaded by you is only some file pointers, not the real wav audios. Please follow the usage steps given in the homepage of the repo. You need to install git-lfs and use it to download the real dataset, which is totally about 200+ GB.
