### ISSUE TITLE
README should indicate that using git-lfs is required 

### ISSUE THREAD

**Issue by hashemelezabi** [microsoft/DNS-Challenge#23]
Without `git-lfs`, the `wav` files that were downloaded seemed to be corrupt or incomplete, causing me to get a `This audio type is not supported` error when running `noisyspeech_synthesizer_multiprocessing.py`. They also took up only around 500MB. With `git-lfs`, `git clone` downloaded around 80GB of data. So using `git-lfs` should not be a recommendation for "faster downloading", but a requirement, unless I'm missing something.

**Comment by hashemelezabi** [comment]
Also, it would be useful to indicate the size of the dataset in the main `README` or the datasets `README`.

**Comment by wenjingyang** [comment]
Totally agree. I had same issue. "git clone" only got 131 byte wave file.

**Comment by motus** [comment]
@hashemelezabi I agree, we have too much data in this repo for LFS to handle. We will remove all datasets from git and host them elsewhere. This way, this repo will not require LFS anymore and we will update the scripts to pull the data (all or part if it) from the hosting location. Stay tuned :)

**Comment by hashemelezabi** [comment]
@motus That sounds great, thanks! Looking forward to it :)
