### ISSUE TITLE
Different lengths

### ISSUE THREAD

**Issue by jonashaag** [microsoft/DNS-Challenge#33]
https://github.com/microsoft/DNS-Challenge/blob/master/datasets/ICASSP_dev_test_set/track_1/synthetic/clean/synthetic_clean_fileid_60.wav 11 s 217 ms
https://github.com/microsoft/DNS-Challenge/blob/master/datasets/ICASSP_dev_test_set/track_1/synthetic/noisy/synthetic_emotion_405613_snr18_tl-26_fileid_60.wav 12 s 0 ms

Is this expected?

**Comment by chandanka90** [comment]
No it is not
