### ISSUE TITLE
Will the subjective evaluation data be released？

### ISSUE THREAD

**Issue by vBaiCai** [microsoft/DNS-Challenge#34]
Hi，organizers, 

The subjective evaluation data is very useful for building an automatic speech assessment system, like DNS-MOS.

So the question is，are you going to release the subjective evaluation data (paired MOS and corresponding speech).

**Comment by chandanka90** [comment]
We have released the DNSMOS API as an Azure service. You can send us an email with your details to get the Auth key. We will not be releasing the subjective evaluation data at this point.
