### ISSUE TITLE
small issue for file path error

### ISSUE THREAD

**Issue by jiminbot20** [microsoft/DNS-Challenge#37]
https://github.com/microsoft/DNS-Challenge/blob/21f730afe97a65d7c944c66b90501cd569905c9b/noisyspeech_synthesizer_singleprocess.py#L173

In 'datasets\impulse_responses' , the slash have to be flipped. 
So 'datasets/impulse_responses' is the correct one.

Unless FileNotFoundError occurs. 

FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\impulse_responses/SLR28/RIRS_NOISES/simulated_rirs/mediumroom/Room059/Room059-00049.wav'

**Comment by vishakg** [comment]
Thanks fixed in master
