### ISSUE TITLE
Some wave files are lost when downloaded by Azcopy

### ISSUE THREAD

**Issue by zelokuo** [microsoft/DNS-Challenge#39]
I've downloaded the wide and full band dataset by azcopy using the SAR_URL,  but lots of wave files are missing, especially in Non-english (french, german, italian, russian, spanish)dataset. The number of files of the clean dataset in this project is about 800k, but I got about 270k files by azcopy. 

I try to download this Non-english dataset from https://www.caito.de/2019/01/the-m-ailabs-speech-dataset/,  but it does not seem to work, So, how can I get the wide and full band non-english dataset.

**Comment by lhy0807** [comment]
I tried to download the dataset using azcopy and find no issues. The only missing part is impulse_responses which I later download directly from openslr.org
