### ISSUE TITLE
Buzzing sound in predictions on model trained with 44.1K sampling rate

### ISSUE THREAD

**Issue by GSC-30212** [microsoft/DNS-Challenge#40]
We generated data set with 44.1K sampling rate by using the process mentioned .

Than we trained a model with this data.

But when we did inferencing as:-

1] For each noisy audio , we did predictions on 10ms window
2] We concat all the 10ms output window to weave back the de-noised audio.

We are hearing buzzing sound in the audio along with the voice.
The same is not observed if we do not do windowing and pass in the whole audio for inferencing.

Please can you help us with the same.

**Comment by chandanka90** [comment]
Did you do overlap and add during synthesis?
