### ISSUE TITLE
Total size of all files?

### ISSUE THREAD

**Issue by zgerrard** [microsoft/DNS-Challenge#41]
Hi, what's the total size of the entire dataset? It would also be helpful to have info on the size of the top level directories, if possible.

Thank you.

**Comment by lhy0807** [comment]
You should expect a number close to 300GB

**Comment by chandanka90** [comment]
It is over 1 TB. If you need specific files, please use this https://github.com/microsoft/DNS-Challenge/blob/master/dns_challenge_data_downloader.py and send us an email requesting SAS_URL
