### ISSUE TITLE
Audio referenced before assignment

### ISSUE THREAD

**Issue by Alberto15Romero** [microsoft/DNS-Challenge#42]
If I run the code as the readme file says, I get this error, after looking at the code, it seems to me that line 41 (inside the try) isn't being correcly executed, any ideas to fix this?

Error:
```
~/DNS-Challenge$ python noisyspeech_synthesizer_singleprocess.py
Number of files to be synthesized: 60000
WARNING: Audio type not supported
Traceback (most recent call last):
  File "noisyspeech_synthesizer_singleprocess.py", line 537, in <module>
    main_body()
  File "noisyspeech_synthesizer_singleprocess.py", line 508, in main_body
    noise_source_files, noise_clipped_files, noise_low_activity_files = main_gen(params)
  File "noisyspeech_synthesizer_singleprocess.py", line 168, in main_gen
    gen_audio(True, params, clean_index)
  File "noisyspeech_synthesizer_singleprocess.py", line 132, in gen_audio
    build_audio(is_clean, params, index, audio_samples_length)
  File "noisyspeech_synthesizer_singleprocess.py", line 82, in build_audio
    input_audio, fs_input = audioread(source_files[idx])
  File "/home/alberto/DNS-Challenge/audiolib.py", line 45, in audioread
    if len(audio.shape) == 1:  # mono
UnboundLocalError: local variable 'audio' referenced before assignment
```

**Comment by Rodolfo-S** [comment]
There's a few closed issues about this saying that "git lfs has to be used" to download the audio files.

**Comment by chandanka90** [comment]
There is some problem with your audio file. Please clone the repo or use this to download https://github.com/microsoft/DNS-Challenge/blob/master/dns_challenge_data_downloader.py

**Comment by motus** [comment]
@Alberto15Romero yes, as Chandan @chandanka90 has pointed out, this error is caused by the Python `soundfile.read()` failure to read the audio file. nevertheless, our code should be a bit smarter about handling such errors. We've fixed the code in the new release and will publish it soon. Thanks for reporting the issue!
