### ISSUE TITLE
Cloning the repo has huge space requirements.

### ISSUE THREAD

**Issue by Rodolfo-S** [microsoft/DNS-Challenge#43]
I cloned the repo last year for the interspeech 2020 version of the dataset. Now that I'm cloning again for the Iatest version, on a new machine, I'm not able to complete the clone. I've gotten insufficient disk space errors twice already. I'm cloning onto an empty 1TB nvme drive.

**Comment by Rodolfo-S** [comment]
![image](https://user-images.githubusercontent.com/37642463/111511438-bd517b80-871c-11eb-8091-a577524406d0.png)
I went and bought a 2TB SSD and the clone finished at 1.8TB. There's a recent issue open stating that the dataset is around 300GB. What am I missing?

**Comment by dofuuz** [comment]
When I clone repository, `datasets` (16k) is around 300GB, `datasets_fullband` (48k) is around 600GB.
`.git` takes another 900~GB for tracking. So I think it's OK.

**Comment by jackhwalters** [comment]
Is there a way to create the dataset so that it contains less files? I'm using it for uni coursework and we don't need to train on full datasets.

**Comment by jackhwalters** [comment]
> Is there a way to create the dataset so that it contains less files? I'm using it for uni coursework and we don't need to train on full datasets.

I just found this for anyone wondering the same thing. https://github.com/microsoft/MS-SNSD

**Comment by chandanka90** [comment]
Please use this script with SAS_URL https://github.com/microsoft/DNS-Challenge/blob/master/dns_challenge_data_downloader.py

**Comment by hlx666548** [comment]
> > Is there a way to create the dataset so that it contains less files? I'm using it for uni coursework and we don't need to train on full datasets.
> 
> I just found this for anyone wondering the same thing. https://github.com/microsoft/M

> > Is there a way to create the dataset so that it contains less files? I'm using it for uni coursework and we don't need to train on full datasets.
> 
> I just found this for anyone wondering the same thing. https://github.com/microsoft/MS-SNSD

You are my god! thank u !!

**Comment by Rodolfo-S** [comment]
> Please use this script with SAS_URL https://github.com/microsoft/DNS-Challenge/blob/master/dns_challenge_data_downloader.py

I don't have the SAS URL. I emailed dns_challenge@microsoft.com on March 18th and never got a response.

**Comment by ttklm20** [comment]
git clone   --depth 1  https://github.com/microsoft/DNS-Challenge.git

**Comment by motus** [comment]
@Rodolfo-S we are removing all audio data from this repo and will host it elsewhere. This way, this repo will not require LFS and we will update the download scripts so you can pull the data (all or part of it) from the hosting location.

**Comment by sc0ttms** [comment]
> Is there a way to create the dataset so that it contains less files? I'm using it for uni coursework and we don't need to train on full datasets.

@jackhwalters

I use the following method to get less files(eg: datasets/noise)

- mkdir DNS-Challenge
- cd DNS-Challenge
- git init
- git remote add origin https://github.com/microsoft/DNS-Challenge.git
- git lfs install --skip-smudge
- git fetch
- git pull origin master
- git lfs install
- git lfs pull --include="datasets/noise"

you can replace “datasets/noise” to get other files or dir

**Comment by motus** [comment]
ok folks this is a non-issue now. I've removed all datasets from git so LFS is no longer required and you need at most 900GB to download the data (829GB, actually) which is 1/2 of the old git repo size.
