### ISSUE TITLE
active_rms noise segment dB RMS calc is not RMS

### ISSUE THREAD

**Issue by Rodolfo-S** [microsoft/DNS-Challenge#44]
In the function `active_rms` [where the rms of the noise segment is calculated](https://github.com/microsoft/DNS-Challenge/blob/959a6f4371f9173d7e0add886ff7d32107994566/audiolib.py#L204), the variable name is `noise_seg_rms` but the the calculation is not RMS. The log10 of the mean-square of the samples is being multiplied by 20.

**Comment by motus** [comment]
Good catch, @Rodolfo-S ! We'll fix it in the new release
