### ISSUE TITLE
How to download the test set that in dev_testset folder? 

### ISSUE THREAD

**Issue by XIEchoAH** [microsoft/DNS-Challenge#45]
Hi,

I want to use part of the DNS dataset, and I downloaded the clean and  noise speech according to your  Readme.md file. However, I did not find the link to download the test set  which in dev_testset folder.
   If it is convenient，can you tell me how to download the speech in “DNS-Challenge/datasets/dev_testset/ ”？

Thanks   so much!

**Comment by chandanka90** [comment]
Please send us an email to dns_challenge@microsoft.com. We will provide you with SAS_URL which you can use in this script to download https://github.com/microsoft/DNS-Challenge/blob/master/dns_challenge_data_downloader.py
