### ISSUE TITLE
DNSMOS web-API service

### ISSUE THREAD

**Issue by minikatty** [microsoft/DNS-Challenge#47]
Does the DNSMOS web_API service still work now? The SCORING_URI and AUTH_KEY I applied several months ago can not allow me to use the web_API service. Need I apply them again?

**Comment by motus** [comment]
I think we've closed it for the general public now. We will start it again for the [new DNS challenge](https://www.microsoft.com/en-us/research/academic-program/deep-noise-suppression-challenge-icassp-2022) soon, though - stay tuned!

**Comment by motus** [comment]
DNSMOS service is up and running now. Please reopen the issue if there are any persistent problems with the service
