### ISSUE TITLE
NSNet 2 baseline ONNX model with 512-size STFT and 32ms window

### ISSUE THREAD

**Issue by hashemelezabi** [microsoft/DNS-Challenge#48]
Hello,

In the [paper](https://arxiv.org/pdf/2008.06412.pdf) describing the NSNet 2 baseline, you use an STFT of size 512 with a 32ms square-root Hann window, but in the provided nsnet2 baseline model under `NSNet2-baseline`, you use a size 320 STFT with a 20ms window. Is there a link where I can find the pretrained ONNX model for the 512-size STFT with 32ms window? I'm working on hardware-accelerating NSNet 2 inference using [Spatial](https://spatial-lang.org/), and the FFT algorithm I'm using is the efficient Cooley-Tukey algorithm which requires power-of-2 inputs. Right now I need to pad the input audio frame of size 320 by zeros to reach size 512, after which I discard redundant/useless information from the output frame DFT to get a 161-size feature vector to feed into the provided model (after computing the log-power spectrum). This wastes computation, so having access to the 512-size STFT model would be very helpful.

I can't train it myself because I don't have the compute resources or even the storage to store the training data available at the moment.

**Comment by motus** [comment]
@hashemelezabi I'll check if we have that model laying around and if we can share it. Stay tuned :)

**Comment by vishakg** [comment]
@hashemelezabi check if the new 48khz model uploaded recently works better for your needs.
