### ISSUE TITLE
48KSample impulse response

### ISSUE THREAD

**Issue by testnn76** [microsoft/DNS-Challenge#49]
I want to add reverb data to the 48Ksample training set. 

Should I just use the 16Ksample impulse response or will a new impulse response be uploaded to the datasets_fullband directory?

Thanks!

**Comment by motus** [comment]
@testnn76 please use the IR from `datasets/`

**Comment by motus** [comment]
@hdubey will add 48K sample data and share it for the upcoming DNS Challenge

**Comment by motus** [comment]
@testnn76 we've published the 48KHz-sampled IR data for the new challenge. Please update the repo from the latest master and run the download script, or simply use the direct URL for the IR data only, at https://dns4public.blob.core.windows.net/dns4archive/datasets_fullband/datasets_fullband.impulse_responses_000.tar.bz2
Please feel free to re-open this issue if you still have problems downloading the data. Thank you!
