### ISSUE TITLE
Dataset generation  report

### ISSUE THREAD

**Issue by mpariente** [microsoft/DNS-Challenge#5]
Hi, I'm setting a simple recipe for the challenge [here](https://github.com/mpariente/AsSteroid/tree/dns-challenge/egs/dns_challenge/baseline) and I'm having some question/remarks about the data generation :
- The `.csv` files generated at the end of the scripts don't really make sense, I think columns and lines where inverted. 
- The default SNR range in the config file make lots of almost noiseless utterances, is this the intended behavior? 
- The noise files are saved with the original scale, not with the same scale as the mixture and the scaling factor are saved nowhere.. It would be nice to have the same scale as in the mixture, or at least, have a .csv file with the scaling factor for each utterance.

**Comment by chandanka90** [comment]
Great points!
- The .csv files are just for logging. I agree it is not very useful. You can comment out that if the generated files look good.
- The default SNR goes up to 40 dB. So there are many clips with very little noise in them. We chose this SNR range to cover most of the real-world scenarios. We want the trained noise suppressor to suppress the noise well and also not to distort the speech at higher SNRs. But you can change it depending on your use case.
- Thanks for pointing out. I changed it to return the updated scale.

**Comment by mpariente** [comment]
Sorry for the late reply and thanks for the changes !
