### ISSUE TITLE
Noise files from DEMAND

### ISSUE THREAD

**Issue by amieroten** [microsoft/DNS-Challenge#52]
Hello,

I'm curious how to go about identifying which files in the noise dataset are pulled from the DEMAND dataset. I'd like to use both the DNS21 noise and DEMAND datasets for model training, but am hoping to exclude the DEMAND files from the DNS set. This was pretty straightforward to do for Freesound, but DEMAND is less clear.

Thank you!
Amie

**Comment by motus** [comment]
@amieroten I don't think we have the DEMAND data in our datasets (wideband or fullband). We use a subset of AudioSet and Freesound only. All files that match `grep -E ' [-_0-9a-zA-Z]{11}\.wav'` are from the AudioSet.

**Comment by motus** [comment]
@hadubey will  take a look. Looks like DEMAND is missing from our repo indeed

**Comment by motus** [comment]
I've added DEMAND data to the Azure public storage and included it into the new downloader script for DNS3. @hadubey, do we have to include DEMAND into DNS4 dataset, too?

**Comment by motus** [comment]
@amieroten DEMAND data is online and available as part of the old DNS3 dataset. Please use the `download-dns-challenge-3.sh` script to download the entire dataset, or simply use the URL https://dns3public.blob.core.windows.net/dns3archive/DEMAND.tar.bz2 do get the DEMAND data only. Please feel free to re-open the issue if you still ahve problems downloading the data
