### ISSUE TITLE
DNSmos API serverce problem 

### ISSUE THREAD

**Issue by xiaoyiming** [microsoft/DNS-Challenge#54]
I have obtained SCORING_URI and AUTH_KEY in accordance with the requirements of DNSMOS web_API service. But I got the following problem when using the given demo to predict  the mos of wavs in local:
  'Connection aborted.', RemoteDisconnected('Remote end closed connection without response'
 How could I slove this problem

**Comment by motus** [comment]
I am not sure if the service is up and running at the moment. We will start it again soon for the [new DNS challenge](https://www.microsoft.com/en-us/research/academic-program/deep-noise-suppression-challenge-icassp-2022), though. Stay tuned!

**Comment by motus** [comment]
DNSMOS service is up and running now. Please reopen the issue if there are any persistent problems with the service
