### ISSUE TITLE
Rnnoise training

### ISSUE THREAD

**Issue by vishaldhull09** [microsoft/DNS-Challenge#60]
I want to use this dataset for training RNNoise model. Can anyone explain me how to use this dataset repo..it little complex

**Comment by motus** [comment]
@vishaldhull09 Please refer to the [DNS Challenge page](https://www.microsoft.com/en-us/research/academic-program/deep-noise-suppression-challenge-icassp-2022/) and the [ICASSP 2021 paper](/docs/ICASSP_2021_DNS_challenge.pdf). If you have any specific questions about the dataset, please feel free to open an issue on github and explain your request in detail. Thank you!
