### ISSUE TITLE
Several blobs does not exit

### ISSUE THREAD

**Issue by SiyuanWei** [microsoft/DNS-Challenge#68]
It seems like that 8 files does not exist in the Azure url~
german_speech_031_NA_NA.tar.bz2
french_speech_007_NA_NA.tar.bz2
german_speech_012_NA_NA.tar.bz2
french_speech_019_NA_NA.tar.bz2
german_speech_020_NA_NA.tar.bz2
german_speech_032_NA_NA.tar.bz2
french_speech_006_NA_NA.tar.bz2
french_speech_014_NA_NA.tar.bz2

![image](https://user-images.githubusercontent.com/20530918/144531645-0c0f54b7-0e6e-4a2e-8276-7276d1c9edcf.png)

**Comment by motus** [comment]
Hi @SiyuanWei , sorry about that. I was repackaging the data into more convenient chunks and you probably ran the script when I was in the process of updating our Azure store. Please update the git repo from the latest master and re-run the download script. Make sure you uncomment the actual curl or wget invocation in the script once the dry run is successful. Please feel free to reopen this issue if there are problems with the download still.

P.S. I will add another download script for the Personalized DNS track soon. Stay tuned :)
