### ISSUE TITLE
Some files in the dev_testset_noisy_testclips seem to be identical

### ISSUE THREAD

**Issue by zhaoyj1122** [microsoft/DNS-Challenge#70]
For example:
![1](https://user-images.githubusercontent.com/19679379/144545503-b9132127-5f99-4366-a1ec-8a5b5b316aba.png)

**Comment by motus** [comment]
@zhaoyj1122 thanks for letting us know! I'll check for the duplicates and get back to you with the update soon.

**Comment by motus** [comment]
@zhaoyj1122 yes, we indeed have ten identical files in the test dataset. The files are at `dev_testset_noisy_testclips`:
```
ms_realrec_emotional_speech_crying_1_headphone_chips_pocket_opening_A2H95JVPEKRUWA_1.wav
ms_realrec_emotional_speech_crying_1_headphone_chips_pocket_opening_A2H95JVPEKRUWA_2.wav
ms_realrec_emotional_speech_crying_1_laptop_crying_A72LC42LU78IP.wav
ms_realrec_emotional_speech_crying_2_headphone_air_conditioner_A2H95JVPEKRUWA_1.wav
ms_realrec_emotional_speech_crying_2_headphone_air_conditioner_A2H95JVPEKRUWA_2.wav
ms_realrec_emotional_speech_crying_2_laptop_crying_A72LC42LU78IP.wav
ms_realrec_emotional_speech_yelling_1_headphone_baby_crying_A2H95JVPEKRUWA_1.wav
ms_realrec_emotional_speech_yelling_1_headphone_baby_crying_A2H95JVPEKRUWA_2.wav
ms_realrec_emotional_speech_yelling_2_headphone_dog_barking_A2H95JVPEKRUWA_1.wav
ms_realrec_emotional_speech_yelling_2_headphone_dog_barking_A2H95JVPEKRUWA_2.wav
```
I will clean up the dataset and update the archive on Azure and close this issue afterwards. Meanwhile, please feel free to remove any 9 out of 10 clips in the list. I'll also check our other datasets for the duplicates. Stay tuned!

**Comment by motus** [comment]
looks like `ms_realrec_emotional_speech_crying_1_laptop_crying_A72LC42LU78IP.wav` is the right one

**Comment by zhaoyj1122** [comment]
> looks like `ms_realrec_emotional_speech_crying_1_laptop_crying_A72LC42LU78IP.wav` is the right one. I'll delete the rest

Got it! Thanks a lot for that.

**Comment by motus** [comment]
I've updated the archive on Azure so I think I can close this issue for now. Please open another one if you see duplicates in our other datasets, and I'll do the same. Thanks for your help and good luck!
