### ISSUE TITLE
data download 404 error

### ISSUE THREAD

**Issue by JinmingChe** [microsoft/DNS-Challenge#75]
Excuse me, when I use the download-dns-challenge-4.sh script to download the training data, it reminds me that the data does not exist. It gives HTTP/1.1 404 THE SPECIFIED BLOB DOES NOT EXIST.

**Comment by motus** [comment]
@JinmingChe please check out the latest master from github and run the script again. We were updating the dataset and it is likely that the script and the data were out of sync just when you were running it. I've just re-ran the script and the data is there, but please feel free to reopen the issue if the problem persists.
