### ISSUE TITLE
DNS-MOS API response is extremely slow

### ISSUE THREAD

**Issue by SiyuanWei** [microsoft/DNS-Challenge#78]
Each audio clip takes about 1-2min to get the score dict response ,and  I often get a 502 response.
Is it normal?

**Comment by gafield-liu** [comment]
I also encountered the same problem. Is there any solution?

**Comment by xjchenGit** [comment]
I also encountered the same problem. I have cut the clip to 10 seconds. The DNSMOS need approximately 2mins and the DNSMOS need approximately 3~4mins every clip.

**Comment by SiyuanWei** [comment]
And the api always throws this error:

requests.exceptions.ProxyError: HTTPSConnectionPool(host='dnsmos.azurewebsites.net', port=443): Max retries exceeded with url: /v1/dnsmosp835/score (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 502 Bad Gateway',)))

**Comment by vishakg** [comment]
1-2 mins for a response is definitely not normal. However it can happen during the following circumstances:
1. DNSMOS being a shared free service suffers from a noisy neighbor problem where a single user making abnormally high number of requests can affect other users.
2. Delays can happen when an update is being made to the service.
3. Delays can happen if the input file you are supplying to the service is too long. The MOS is computed for each of the segments and averaged before the score is returned. This can lead to delays.

**Comment by rohithmars** [comment]
Hi,

It seems the DNSMOS service is still quite slow and sometimes, there is no response as well.

Does anyone else face this issue? Or am I missing something?
