### ISSUE TITLE
DNS Noisy Dataset Lables

### ISSUE THREAD

**Issue by nafarieh** [microsoft/DNS-Challenge#87]
Hi, 
How to get DNS Noisy Dataset Lables?

**Comment by motus** [comment]
Clean speech are your labels @nafarieh
Please take a look at the [paper](/microsoft/DNS-Challenge/blob/master/docs/ICASSP_2022_4th_Deep_Noise_Suppression_Challenge.pdf) to see how to generate your training set from clean speech, noise, and IR data.

**Comment by nafarieh** [comment]
Thanks,
In DNS Dataset, the noise dataset includes over 180 hours of clips from 150 classes.
I wanna know whtas lables name are in 150 class?
