### ISSUE TITLE
DNSMOS API response

### ISSUE THREAD

**Issue by rohithmars** [microsoft/DNS-Challenge#97]
Hello,

Most of the requests to the DNSMOS API service is met with <Response [502]> error.

For very short clips (~3s), it is possible to get scores for few samples. However, the service seems to be a bit slow and gets no response in between.

I understand the issue has been raised before, but it still seems not resolved. I am not sure if anyone else still face this issue.

If I am missing something, please let me know.

Thanks!

**Comment by zhaoyj1122** [comment]
@rohithmars same issue here. Quite painful to use this API to get a smooth experience for scoring ...

**Comment by JasonSWFu** [comment]
Is it possible to release a .exe file or the pre-trained model so that everyone can run the model on their local?

**Comment by motus** [comment]
@JasonSWFu that's a great question! I'll assign the issue to @vishakg who's the main driving force behind the service. I am not sure if we'll be able to release the model, but I am pretty sure we can speed up the service and enable batch operation (as mentioned in #71). Stay tuned!

**Comment by daxiong0** [comment]
@vishakg Hello, At present,when I use the DNSMOS scoring tool,the response 502 is still returned to me,which is very unstable.Has it been improved now?thanks.

**Comment by wangshuo182** [comment]
This issue is even worse for me. The <response 502> is returned without exception... @daxiong0

**Comment by rohithmars** [comment]
Hello,

Can anyone confirm whether this issue has been resolved?

@motus  @vishakg Is it possible to speed up the service? I still seem to get the 502 response. 

Thanks a lot!

**Comment by vishakg** [comment]
@daxiong0 , @wangshuo182 @rohithmars I have scaled up the service to handle the huge surge in requests we are seeing at the moment. Like I mentioned earlier, this service being a free service suffers from a noisy neighbor problem where too many requests from a single user result in denial of service to the others.
